[project]
name = "chromadb-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=0.5.16",
    "openai>=1.52.2",
]
